### ISSUE TITLE
Lots of warning messages

### ISSUE THREAD

**Issue by qiahua** [Keksuccino/Linguji#10]
Translating from English to Chinese appeared a lot [Warning] The translation engine returned an invalid number of translation lines! try again..] 

How to modify the tolerance of an invalid number of translation lines?

An 8-minute subtitle took 4 to 5 hours due to a large number of invalid translation lines and a lot of attempts.

Primary Translator Gemini Pro

**Comment by qiahua** [comment]
lines Per Packet 5 is changed to 1, and warning messages are greatly reduced.

**Comment by Keksuccino** [comment]
There's no tolerance for invalid lines, because invalid lines means subtitle lines got removed or merged, which also means the system doesn't know anymore which translated line belongs to which original line.

Reducing the lines per packet to 1 is a good workaround for that specific problem, but it will also make the translation sound wayyy worse. With only one line, Gemini has no context for what the subtitle lines talk about, so it will just _yolo_ it, which is often _bad_.

The invalid lines problem is on Gemini's side and I sadly can't do anything to fix that, sorry.
It is also not really a problem for many other languages, but seems to be in your case (with Chinese)..

In case you changed the prompt, change it back please. Messing with the prompt can also highly increase the "invalid line" warnings.
